homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Copenhagen

frontend:
config:
system_health:
configurator:
http:
api:

#debugpy:
#  wait: true

logger:
  default: warning
  logs:
    custom_components.dukasmartfan: debug
